name: main

on:
  pull_request:
  push:
    branches:
      - master
      - workflows-dev

jobs:
  main:
    runs_on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, pypy3]
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Run test with tox
      run: tox